name: Release Bottles Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/Bottles-appimage/main/bottles-conty-builder.sh
        chmod a+x ./bottles-conty-builder.sh
        ./bottles-conty-builder.sh
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Bottles-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: Bottles-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              Bottles-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
